# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
name: <Repo Name> Image Build and Publish

on:
  workflow_call:
    inputs:
      username:
        required: false
        type: string
    secrets:
      token:
        required: false
        
jobs:
  call-workflow-1:
    uses: submittable/volunteerism-poc/.github/workflows/buildAndPublish.yml@0.21.0
